### ISSUE TITLE
exceptとfilterの実装時期

### ISSUE THREAD

**Issue by kassytech01** [weseek/growi-plugin-lsx#16]
exceptとfilterを使いたいのですが、実装時期は立ってますでしょうか。

**Comment by yuki-takei** [comment]
@kassytech01 
filter オプションは2018年末に実装されました。(READMEの更新を忘れていたのでたった今更新しました)
except オプションの実装は今のところ予定していませんが、要望が多ければすぐ実装可能かなと思います。

**Comment by NoMoreOrange** [comment]
growi-plugin-lsxの使い方を調べていてたどり着きました。
exceptオプションの実装は予定していないということで、若干落胆しておりますが
いつの日か実装されることを期待して首をながーくしてお待ちしております。

**Comment by naomichi-y** [comment]
ユーザが増えてくると、トップページの`/user`リストが長くなり可読性が落ちるため、実装を希望します。
(もしくは他の方法で`/user`を除外する方法ありますでしょうか?)

**Comment by yuki-takei** [comment]
@kassytech01 @NoMoreOrange @naomichi-y 
v3.0.7 で実装しました。

## Examples
```
$lsx(/,except=^user)
```
で、`/user` で始まるものを除外。

```
$lsx(/, except=user|hoge|fuga)
```

で、user, hoge, fuga をページパスに含むものを全て除外。

## 利用方法
- オンプレで利用中の方はインストール済みの growi-plugin-lsx をアップグレードしてからクライアントビルド、サーバー再起動を行ってください
- 公式 docker image をご利用の方は本体バージョン v3.6.0 のリリースをお待ちください

**Comment by yuki-takei** [comment]
ただちょっと使いにくいところも…

## メモ
[/資料/内部仕様/growi-lsx-plugin](https://dev.growi.org/5df1524078911d00512724a3)

**Comment by naomichi-y** [comment]
@yuki-takei 
ありがとうございます!
現在growi.cloudを利用しており、インストールされてるバージョンは3.0.3のようですが、こちらのアップデート時期はいつ頃を予定されてますでしょうか?

**Comment by yuki-takei** [comment]
GROWI.cloud のバージョンはお客様の方でアップグレードしていただく形になっています。
こちらをご覧ください。

[/FAQ/アプリについて/バージョンについて](https://help.growi.cloud/5dc5032861b17d004521ded7)
